name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]
    env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        SEC_KEY: ${{secrets.SEC_KEY}}
        SP_API_KEY: ${{secrets.SP_API_KEY}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx prisma db push
    
