name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Push Prisma Schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SP_API_KEY: ${{ secrets.SP_API_KEY }}
          SEC_KEY: ${{ secrets.SEC_KEY }}
        run: npx prisma db push

      - name: Create Env file
        run: |
          touch .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "SP_API_KEY=${{ secrets.SP_API_KEY }}" >> .env
          echo "SEC_KEY=${{ secrets.SEC_KEY }}" >> .env

      - name: Start or Restart PM2 Process
        run: |
          # Check if the 'bs-backend' process is running
          if pm2 list | grep -q 'bs-backend'; then
            echo "Restarting bs-backend..."
            pm2 restart bs-backend
          else
            echo "Starting bs-backend..."
            pm2 start npm --name bs-backend -- run start
          fi
